### ISSUE TITLE
Tiltfile error

### ISSUE THREAD

**Issue by furkatgofurov7** [Nordix/airship-clusterapi-docs#31]
Got a build error in the tilt: 
```
Starting Tilt (v0.12.8, built 2020-03-12)…
Beginning Tiltfile execution
Successfully loaded Tiltfile (5.071517ms)
Traceback (most recent call last):
  /home/furkat/First Task/capi/capi-dev/Tiltfile:9:17: in <toplevel>
  <builtin>: in default_registry
Error: default_registry: for parameter host: got NoneType, want string
```
There is no host parameter in the Tiltfile

**Comment by furkatgofurov7** [comment]
@kashifest can you please give some hints?

**Comment by kashifest** [comment]
Can you give some more details? What are you trying to run?

**Comment by kashifest** [comment]
If in case you are trying to install CAPI-dev, follow this PR instead, https://github.com/Nordix/airship-clusterapi-docs/pull/29/

**Comment by furkatgofurov7** [comment]
> @kashifest can you please give some hints?

I was following this [https://github.com/Nordix/airship-clusterapi-docs/tree/master/capi-dev](url) document and after running `tilt up` command at the end I got the above provided error

**Comment by kashifest** [comment]
@furkatgofurov7  that was made for v1alpha2, a lot has changed since then and I believe the information has become obsolete now. @jan-est has played with it recently and the above link that I gave is his PR, so he can also give some directions in-case you have some issues.

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 that was made for v1alpha2, a lot has changed since then and I believe the information has become obsolete now. @jan-est has played with it recently and the above link that I gave is his PR, so he can also give some directions in-case you have some issues.

Thanks @kashifest for information, forgot to check when the document was created.
